#!/usr/bin/env python3
"""
Convert a TFLite flatbuffer to a C array for Arduino TFLite Micro embedding.

Generates two files:
  <output-dir>/model_data.h    — extern declarations
  <output-dir>/model_data.cpp  — const byte array + length variable

Usage
-----
python scripts/tflite_to_c_array.py \\
    --tflite   models/har_cnn_int8.tflite \\
    --output-dir arduino/har_inference/ \\
    --var-name g_har_model

The generated files are used by the Arduino sketch:
    #include "model_data.h"
    const tflite::Model* model = tflite::GetModel(g_har_model_data);
"""

import argparse
import math
import os
from datetime import datetime
from pathlib import Path


HEADER_TEMPLATE = """\
// model_data.h — AUTO-GENERATED by scripts/tflite_to_c_array.py
// Source : {source}
// Date   : {date}
// Size   : {size_bytes} bytes ({size_kb:.1f} KB)
//
// DO NOT EDIT — regenerate with:
//   python scripts/tflite_to_c_array.py --tflite {source} --output-dir <dir>

#pragma once

#ifdef __cplusplus
extern "C" {{
#endif

extern const unsigned char {var}_data[];
extern const unsigned int  {var}_len;

#ifdef __cplusplus
}}
#endif
"""

IMPL_TEMPLATE = """\
// model_data.cpp — AUTO-GENERATED by scripts/tflite_to_c_array.py
// Source : {source}
// Date   : {date}
// Size   : {size_bytes} bytes ({size_kb:.1f} KB)

#include "model_data.h"

// Model weights — placed in Flash (PROGMEM on AVR; regular Flash on ARM Cortex-M)
// nRF52840 (Cortex-M4F): no PROGMEM needed; flash is directly addressable.
alignas(8) const unsigned char {var}_data[] = {{
{array_body}
}};

const unsigned int {var}_len = {size_bytes}U;
"""


def to_c_array(data: bytes, cols: int = 12) -> str:
    """Format bytes as a C hex literal array body."""
    rows = []
    for i in range(0, len(data), cols):
        chunk = data[i : i + cols]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        rows.append(f"  {hex_vals},")
    return "\n".join(rows)


def main() -> None:
    p = argparse.ArgumentParser(
        description="Convert TFLite model to C array for TFLite Micro"
    )
    p.add_argument("--tflite",      required=True,  help="Path to .tflite file")
    p.add_argument("--output-dir",  required=True,  help="Output directory for .h/.cpp")
    p.add_argument("--var-name",    default="g_har_model",
                   help="C variable name prefix (default: g_har_model)")
    p.add_argument("--cols",        type=int, default=12,
                   help="Hex values per row (default: 12)")
    args = p.parse_args()

    tflite_path = Path(args.tflite)
    if not tflite_path.exists():
        raise FileNotFoundError(f"TFLite file not found: {tflite_path}")

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    data      = tflite_path.read_bytes()
    size      = len(data)
    size_kb   = size / 1024
    source    = str(tflite_path)
    date      = datetime.now().strftime("%Y-%m-%d %H:%M")
    var       = args.var_name
    arr_body  = to_c_array(data, cols=args.cols)

    h_path   = out_dir / "model_data.h"
    cpp_path = out_dir / "model_data.cpp"

    h_path.write_text(HEADER_TEMPLATE.format(
        source=source, date=date, size_bytes=size, size_kb=size_kb, var=var
    ))
    cpp_path.write_text(IMPL_TEMPLATE.format(
        source=source, date=date, size_bytes=size, size_kb=size_kb,
        var=var, array_body=arr_body
    ))

    print(f"Generated C array for {size:,} bytes ({size_kb:.1f} KB):")
    print(f"  {h_path}")
    print(f"  {cpp_path}")
    print(f"\nIn your Arduino sketch:")
    print(f"  #include \"model_data.h\"")
    print(f"  const tflite::Model* model = tflite::GetModel({var}_data);")
    print(f"  // Check: {var}_len == {size}")

    # Print memory estimate for nRF52840
    tensor_arena_estimate = 49152   # ~48 KB conservative estimate
    total_ram = tensor_arena_estimate
    total_flash = size
    print(f"\nnRF52840 memory estimate:")
    print(f"  Flash (model C array): {total_flash/1024:.1f} KB  "
          f"(of 1024 KB available)")
    print(f"  RAM   (tensor arena):  {tensor_arena_estimate/1024:.0f} KB  "
          f"(of 256 KB available)")


if __name__ == "__main__":
    main()
